# Generated by Django 2.2.1 on 2019-06-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0007_auto_20190606_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktest1',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.Student'),
        ),
    ]
